<?php

namespace MultiTenantSaas\Services\Mcp;

use MultiTenantSaas\Contracts\McpToolRegistryContract;

/**
 * MCP Skill 文件生成器
 *
 * 根据注册的 MCP 工具自动生成 Skill 定义文件。
 * 支持两种输出格式：
 * - Markdown Skill: 用于 WorkBuddy 等客户端
 * - JSON 配置: 用于 Hermers/OpenClaw 等客户端
 */
class McpSkillGenerator
{
    public function __construct(
        private McpToolRegistryContract $toolRegistry,
        private McpClientRegistry $clientRegistry
    ) {}

    public function getClientRegistry(): McpClientRegistry
    {
        return $this->clientRegistry;
    }

    /**
     * 生成 Markdown Skill 格式
     */
    public function generateMarkdownSkill(string $clientSlug, string $skillName = 'SaaS Platform Tools'): string
    {
        $tools = $this->toolRegistry->all();
        $lines = [];

        $lines[] = "# {$skillName}";
        $lines[] = '';
        $lines[] = "Generated by Multi-Tenant SaaS MCP Server for {$clientSlug}";
        $lines[] = '';

        $categories = $tools->groupBy(function ($tool) {
            return $tool['inputSchema']['_category'] ?? 'general';
        });

        foreach ($categories as $category => $categoryTools) {
            $lines[] = "## " . ucfirst($category);
            $lines[] = '';

            foreach ($categoryTools as $tool) {
                $lines[] = "### {$tool['name']}";
                $lines[] = '';
                $lines[] = $tool['description'] ?? 'No description';
                $lines[] = '';
                $lines[] = '**Parameters:**';
                $lines[] = '';

                $properties = $tool['inputSchema']['properties'] ?? [];
                $required = $tool['inputSchema']['required'] ?? [];

                foreach ($properties as $paramName => $paramDef) {
                    $type = $paramDef['type'] ?? 'string';
                    $desc = $paramDef['description'] ?? '';
                    $isRequired = in_array($paramName, $required) ? ' (required)' : '';

                    $lines[] = "- `{$paramName}`: {$type}{$isRequired} - {$desc}";
                }

                $lines[] = '';
            }
        }

        return implode("\n", $lines);
    }

    /**
     * 生成 JSON 配置格式
     */
    public function generateJsonConfig(string $clientSlug): array
    {
        $tools = $this->toolRegistry->all();
        $client = $this->clientRegistry->getClient($clientSlug);

        $config = [
            'server' => [
                'name' => 'multi-tenant-saas-mcp',
                'version' => '1.0.0',
                'protocol' => 'json-rpc-2.0',
            ],
            'client' => $client ? [
                'name' => $client->name,
                'slug' => $client->slug,
                'output_format' => $client->output_format,
            ] : null,
            'tools' => [],
        ];

        foreach ($tools as $tool) {
            $config['tools'][] = [
                'name' => $tool['name'],
                'description' => $tool['description'],
                'inputSchema' => $tool['inputSchema'],
            ];
        }

        return $config;
    }

    /**
     * 根据客户端类型生成对应格式
     */
    public function generate(string $clientSlug, ?string $format = null): string|array
    {
        $format = $format ?? $this->clientRegistry->getOutputFormat($clientSlug);

        return match ($format) {
            'markdown_skill' => $this->generateMarkdownSkill($clientSlug),
            default => $this->generateJsonConfig($clientSlug),
        };
    }

    /**
     * 批量生成所有客户端的 Skill 文件
     */
    public function generateAll(): array
    {
        $result = [];
        $clients = $this->clientRegistry->getClients();

        foreach ($clients as $client) {
            $result[$client->slug] = $this->generate($client->slug, $client->output_format);
        }

        return $result;
    }
}